version: "3"
services:
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.6.1
    ports:
      - "9081:9080"
    volumes:
      - logs:/var/log
    command: -config.file=/etc/promtail/config.yml

  api:
    build: sample-django
    ports:
      - 8000:8000
    command: ["opentelemetry-instrument", "gunicorn", "mysite.wsgi", "--workers", "2", "--threads", "2", "--reload", "--bind", "0.0.0.0:8000"]
    volumes:
      - logs:/var/log
    environment:
      - OTEL_EXPORTER_OTLP_INSECURE=True
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4317
      - OTEL_SERVICE_NAME=sample-api
      - OTEL_METRICS_EXPORTER=none
      # - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=otel:4317
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - HTTP_SERVER_URL=http://api-2:8000/polls/
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

  api-2:
    build: sample-django
    ports:
      - 8001:8000
    command: ["opentelemetry-instrument", "gunicorn", "mysite.wsgi", "--workers", "2", "--threads", "2", "--reload", "--bind", "0.0.0.0:8000"]
    volumes:
      - logs:/var/log
    environment:
      - OTEL_EXPORTER_OTLP_INSECURE=True
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4317
      - OTEL_SERVICE_NAME=sample-api-2
      - OTEL_METRICS_EXPORTER=none
      # - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=otel:4317
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,api,api-2

  otel:
    image: otel/opentelemetry-collector:0.61.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector.yaml

  tempo:
    image: grafana/tempo:2.4.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo-local.yaml:/etc/tempo.yaml
      - ./.data/tempo-data:/tmp/tempo
    ports:
      - 4318:4318

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - ./observability/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoApmTable
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./observability/nginx.conf:/etc/nginx/nginx.conf
      - ./observability/nginx_global_auth:/etc/nginx/auth/global_auth
    ports:
     - 80:80

volumes:
  logs:
